version: '3.9'

services:
  web:
    build: .
    command: gunicorn hacker_news.wsgi -b 0.0.0.0:8000
    environment:
      - SECRET_KEY=django-insecure-e!p8^$$3!ajr83_#_k=0k+$$b_&ocn8+pwj6el)w=v47jjcm@%at
      - DEBUG=1
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: